### ISSUE TITLE
Mad Level 1 - Example (Gradle buildFeatures)

### ISSUE THREAD

**Issue by louie1966** [pmeijer-hva/mad-codelabs#11]
Ik heb hier toch een tijdje op gezeten.

Bij mij ging viewBinding pas werken toen ik het '=' teken verwijderd had.

```
android {
    ...
    buildFeatures {
        viewBinding = true
    }
}
```

groet René de Leeuw

**Comment by remideboerhva** [comment]
Dat is helaas weer een verandering in de nieuwere versies, handig om dat erbij te vermelden.
[link](https://developer.android.com/topic/libraries/view-binding)

**Comment by bradian** [comment]
This is interesting but not a defect as both of them work.  I will therefore close this.

**Comment by Marcellis** [comment]
Without = is in de Android documentation

**Comment by bradian** [comment]
Changed the example to 
buildFeatures {
        viewBinding true
    }
and added a comment about the video being different.
