### ISSUE TITLE
MadLevel5Task1 - Onduidelijke instructies

### ISSUE THREAD

**Issue by kemmel-dev** [pmeijer-hva/mad-codelabs#12]
Ik kom er halverwege de opdracht achter dat het bij deze opdracht niet de bedoeling is om een app te bouwen waar in je meerdere notities kan opslaan (zoals de Reminders app bijv.), maar de bedoeling dat je een app bouwt waarbij er maar 1 notitieveld is dat je bewerkt.
In het gifje lijkt het namelijk net alsof je meerdere van dat soort notes onder elkaar zou kunnen toevoegen. Nu kom ik toch een beetje in de knoop met de opbouw van mijn app omdat ik het dus meerdere notities onder elkaar in gedachten had.
Wellicht het waard om dit er even bij te verduidelijken aan het begin.

**Comment by bradian** [comment]
I have extended the opening comments of this exercise to explain that only one note at a time is in the app.
