### ISSUE TITLE
Instructions list the wrong file

### ISSUE THREAD

**Issue by kemmel-dev** [pmeijer-hva/mad-codelabs#3]
Typo found in Level 1, Task 1 ( https://mad-codelabs.azurewebsites.net/codelabs/level1-task1/ )

Step 2 contains:

![image](https://user-images.githubusercontent.com/8700780/107153046-cb68eb00-696b-11eb-9a56-369897932480.png)

Which should be

"Just like the example, make sure to enable viewbinding in `app/build.gradle`."

**Comment by pmeijer-hva** [comment]
Bedankt voor het inschieten! We gaan het fixen.

**Comment by bradian** [comment]
I have correct this
