### ISSUE TITLE
Level 3 Task 1 - Missing text

### ISSUE THREAD

**Issue by develine** [pmeijer-hva/mad-codelabs#4]
"Alter the fragment_rating.xml so that it matches the image on the left. You can use the **???????????** element for the stars. The game name will be randomized later."

Het element staat er niet.

**Comment by kemmel-dev** [comment]
Ik kwam deze fout ook net tegen, maar kwam deze issue al tegen. De bovenstaande commit die het fixt staat nog niet online. Dacht ik zeg het even, voor het geval dat jullie daar nog niet van op de hoogte zijn.

**Comment by pmeijer-hva** [comment]
Hmm dit lijkt op een bug in de codelabs. Hij parsed die tag niet goed. Is wel meegenomen in de build, de commit
