### ISSUE TITLE
Level 3 Task 2 - Parcelize plugin

### ISSUE THREAD

**Issue by develine** [pmeijer-hva/mad-codelabs#5]
Het is niet duidelijk welke extension of plugin je nodig hebt voor Parcelize. Je vindt dit ook niet snel online, omdat de meeste oplossingen die online staan oud zijn en daarom ook niet werken. Misschien kunnen jullie dit erbij zetten? Ik gebruik zelf:
plugins {  id  'kotlin-android-extensions' }

**Comment by pmeijer-hva** [comment]
Ja volgens mij hoef je niks meer te enablen in gradle. Dat moest in het verleden expliciet gedaan worden. Ik laat hem even open nog het issue en dan gaan we er nog naar kijken. Dank voor melding :)

**Comment by Marcellis** [comment]
Het gaat niet automatisch.

**Comment by bradian** [comment]
Yes - I agree - I have been struggling to get this to work and it is taking far more time than it should.

**Comment by bradian** [comment]
I have added something to the Level 2 Task 2 which I hope will help.
