### ISSUE TITLE
Level 4 task 2 - fragment onOptionsItemSelected & back arrow

### ISSUE THREAD

**Issue by develine** [pmeijer-hva/mad-codelabs#7]
- Het was voor mij niet duidelijk dat een fragment een onOptionsItemSelected kan hebben en dat je in de onViewCreated methode setHasOptionsMenu(true) moest neerzetten om het te laten werken. 
- Aangeven hoe je een backarrow kan enablen, zonder er veel voor te hoeven doen. In mainActivity:
setupActionBarWithNavController(navHostFragment.navController)

**Comment by bradian** [comment]
I have changed the instruction file for Level 4 Task 2 to give some guidance on how to do this.
