### ISSUE TITLE
mad level 2 task 1

### ISSUE THREAD

**Issue by Marcellis** [pmeijer-hva/mad-codelabs#8]
The two arrays should not be separate, but integrated.

**Comment by pmeijer-hva** [comment]
Marco! Please provide some more detail. Like in which step it can be found etc. In this case i do think what you are talking about. This causes students to seperate the arrays as well in the following levels. Which is not the best solution

**Comment by Marcellis** [comment]
Step 2.

**Comment by bradian** [comment]
The only choice was to re-write sections of the app and update the instructions.  We now a single array of Place objects.  I think this is a much better OO solution.  I couldn't push to Marco's github and we want to move to Gitlab anyway so the solution is in my Gitlab.
