### ISSUE TITLE
MadLevel4Task1 application name

### ISSUE THREAD

**Issue by kemmel-dev** [pmeijer-hva/mad-codelabs#9]
Nog een vrij _arbitrary_ foutje, maar op de pagina van Level 4 Task 1 staat nog Name the application ‘MadLevel3Task1'. Denk dat de meesten hier wel uitkomen ;)

**Comment by louie1966** [comment]
Ik kwam er ook uit. :-)

**Comment by bradian** [comment]
I have corrected this.
